
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arbaaz Makandar
 */
public class RetireVehicle extends javax.swing.JFrame {
   /* Thread t=new Thread(new Runnable()
    {
        public void run()
    {   
        DefaultTableModel dc1 = (DefaultTableModel)tb_vehicle.getModel();
         while(true)
        {   
                   
            if( (""+dc1.getValueAt(tb_vehicle.getSelectedRow(),0)).equals(""))
                { 
                   bt_retire.setEnabled(false);
                }
            else if(!((""+dc1.getValueAt(tb_vehicle.getSelectedRow(),0)).equals("")))
              bt_retire.setEnabled(true);
        }
    }
    });
    */
    /**
     * Creates new form RetireVehicle
     */
    public RetireVehicle() {
        initComponents();
        itembharo();
       //t.start();
    }
    
    public void itembharo()
    {
        DefaultTableModel dc1= (DefaultTableModel)tb_vehicle.getModel();
        Connection cn=null;
        Statement st=null;
        ResultSet rs=null,rs1=null;
        String sql="select * from vehicle order by status;";
        try
        {
                try
                    {
                        Class.forName("java.sql.Driver");
                        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tavs","root","1234");
                        st=cn.createStatement();
                        rs=st.executeQuery(sql);
                        dc1.setRowCount(0);
                            while(rs.next())
                                {
                                  Object a=""+rs.getInt(1);
                                  Object b=rs.getString(2);
                                  Object c=rs.getString(3);
                                  Object d=rs.getString(4);
                                  Object e=""+rs.getInt(5);
                                  Object f=""+rs.getInt(6);
                                  Object g=""+rs.getInt(7);
                                  Object h=rs.getString(8);
                                  Object obj[]= {a,c,b,d,e,f,g,h};
                                  dc1.addRow(obj);
                                }
                          
                             
                    }
                 catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                finally
                {
                  rs.close();
                  st.close();
                  cn.close();
                
                }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_vehicle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_retire = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tb_vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "V_id", "Company", "Vehicle Name", "Type", "Price(per hr)", "Price(per km)", "Price(min)", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_vehicle);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setText("Retire Vehicle");

        bt_retire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_retire.setText("Retire Vehicle");
        bt_retire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retireActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_back.setText("GO BACK");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(bt_retire, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_retire, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_retireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retireActionPerformed
     DefaultTableModel dc1= (DefaultTableModel)tb_vehicle.getModel();
     if(tb_vehicle.getSelectedRow()==-1)
     {
         JOptionPane.showMessageDialog(null,"!!!Select a vehicle!!!");
     }
     else if(dc1.getValueAt(tb_vehicle.getSelectedRow(),7).equals("RENTED"))
     {
         JOptionPane.showMessageDialog(null,"Rented Vehicles can't be retired, wait for the return of vehicle");
     }
     else if(dc1.getValueAt(tb_vehicle.getSelectedRow(),7).equals("RETIRED"))
     {
         JOptionPane.showMessageDialog(null,"Vehicle Already retired!! Try other Vehicles");
     }
     
     else if(dc1.getValueAt(tb_vehicle.getSelectedRow(),7).equals("AVAILABLE") || dc1.getValueAt(tb_vehicle.getSelectedRow(),7).equals("REPAIRING"))
     {
         String V_id= ""+dc1.getValueAt(tb_vehicle.getSelectedRow(),0);   
         Connection cn=null;
            Statement st=null;
            ResultSet rs= null;

            try
            {
                try
                {
                    Class.forName("java.sql.Driver");
                    cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tavs","root","1234");
                    st=cn.createStatement();
                    
                    String sql4="update vehicle set status = 'RETIRED' where V_id ="+V_id+" ;" ;
                    st.executeUpdate(sql4);
                    /*
                    String sql3="update vehicle set status = 'RENTED' where V_id = "+tf_id.getText()+";";
                    st.executeUpdate(sql3);
                    */
                    JOptionPane.showMessageDialog(null,"record saved, Vehicle Retired Successful");
                    itembharo();
                }

                catch(Exception e)

                {
                    JOptionPane.showMessageDialog(null,e.getMessage());

                }
                finally
                {

                    st.close();
                    cn.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
         
     }
// TODO add your handling code here:
    }//GEN-LAST:event_bt_retireActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
      //  t.stop();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetireVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetireVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetireVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetireVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetireVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_retire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_vehicle;
    // End of variables declaration//GEN-END:variables
}
