/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author arbaa
 */

public class VehicleHistory extends javax.swing.JFrame {
       String Global = "";
    /**
     * Creates new form VehicleHistory
     */
    public VehicleHistory() {
        initComponents();
        List<String> vehicleNames = getVehicles();
        vehicleNames.add(0,"Select A Vehicle");
        String[] v = vehicleNames.toArray(new String[0]); 
        vehicleCombo.setModel(new DefaultComboBoxModel<>(v));
        
    }
    
  public List<String> getVehicles(){
      
       String sql="select DISTINCT V_name from vehicle;";
        Connection cn=null;
        Statement st=null;
        ResultSet rs=null,rs1=null;
        List<String> vehicleNames =new ArrayList <String>();
       try
        {
                try
                    {
                        Class.forName("java.sql.Driver");
                        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tavs","root","1234");
                        st=cn.createStatement();
                        rs=st.executeQuery(sql);
                        
                            while(rs.next())
                                {
                                  vehicleNames.add(rs.getString("V_name"));
                                  
                                }
                          
                             
                    }
                 catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                finally
                {
                  rs.close();
                  st.close();
                  cn.close();
                
                }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
       return vehicleNames;
      
  }  
 public void itembharo()
    {
        DefaultTableModel dc1= (DefaultTableModel)vehiclebooking_history.getModel();
        Connection cn=null;
        Statement st=null;
        ResultSet rs=null,rs1=null;
        String sql="select * from BookingHistory where V_name = '"+Global +"';";
        try
        {
                try
                    {
                        Class.forName("java.sql.Driver");
                        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tavs","root","1234");
                        st=cn.createStatement();
                        rs=st.executeQuery(sql);
                        dc1.setRowCount(0);
                            while(rs.next())
                                {
                                  Object a=""+rs.getInt(5);
                                  Object b=rs.getString(6);
                                  Object c=rs.getString(7);
                                  Object d=rs.getString(2);
                                  Object e=rs.getString(8);
                                  Object f=rs.getString(9);
                                  Object g=""+rs.getInt(10);
                                  Object h=""+rs.getInt(11);
                                  
                                  Object obj[]= {a,b,c,d,e,f,g,h};
                                  dc1.addRow(obj);
                                }
                          
                             
                    }
                 catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                finally
                {
                  rs.close();
                  st.close();
                  cn.close();
                
                }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehiclebooking_history = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        vehicleCombo = new javax.swing.JComboBox<>();
        getHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setText("Vehicle Booking History");

        vehiclebooking_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Vehicle Name", "Vehicle Type", "Customer Name", "Pickup Date", "Return Date", "Distance Travelled", "Total Fare"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vehiclebooking_history);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        vehicleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vehicleCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleComboItemStateChanged(evt);
            }
        });

        getHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getHistory.setText("GET HISTORY");
        getHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(297, 297, 297))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vehicleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getHistory)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehicleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vehicleComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleComboItemStateChanged
        // TODO add your handling code here:
        String vehicleStr = vehicleCombo.getSelectedItem().toString();
        Global = vehicleStr;
        
    }//GEN-LAST:event_vehicleComboItemStateChanged

    private void getHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getHistoryActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dc1 = (DefaultTableModel)vehiclebooking_history.getModel();
        dc1.setRowCount(0);
        itembharo();
        
    }//GEN-LAST:event_getHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getHistory;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> vehicleCombo;
    private javax.swing.JTable vehiclebooking_history;
    // End of variables declaration//GEN-END:variables
}
